// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'preinscription_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PreinscriptionModel _$PreinscriptionModelFromJson(Map<String, dynamic> json) =>
    PreinscriptionModel(
      id: (json['id'] as num?)?.toInt(),
      uuid: json['uuid'] as String?,
      uniqueCode: json['uniqueCode'] as String?,
      faculty: json['faculty'] as String,
      lastName: json['lastName'] as String,
      firstName: json['firstName'] as String,
      middleName: json['middleName'] as String?,
      dateOfBirth: DateTime.parse(json['dateOfBirth'] as String),
      isBirthDateOnCertificate: json['isBirthDateOnCertificate'] as bool,
      placeOfBirth: json['placeOfBirth'] as String,
      gender: json['gender'] as String,
      cniNumber: json['cniNumber'] as String?,
      residenceAddress: json['residenceAddress'] as String,
      maritalStatus: json['maritalStatus'] as String,
      phoneNumber: json['phoneNumber'] as String,
      email: json['email'] as String,
      firstLanguage: json['firstLanguage'] as String,
      professionalSituation: json['professionalSituation'] as String,
      previousDiploma: json['previousDiploma'] as String?,
      previousInstitution: json['previousInstitution'] as String?,
      graduationYear: (json['graduationYear'] as num?)?.toInt(),
      graduationMonth: json['graduationMonth'] as String?,
      desiredProgram: json['desiredProgram'] as String?,
      studyLevel: json['studyLevel'] as String?,
      specialization: json['specialization'] as String?,
      seriesBac: json['seriesBac'] as String?,
      bacYear: (json['bacYear'] as num?)?.toInt(),
      bacCenter: json['bacCenter'] as String?,
      bacMention: json['bacMention'] as String?,
      gpaScore: (json['gpaScore'] as num?)?.toDouble(),
      rankInClass: (json['rankInClass'] as num?)?.toInt(),
      birthCertificatePath: json['birthCertificatePath'] as String?,
      cniPath: json['cniPath'] as String?,
      diplomaPath: json['diplomaPath'] as String?,
      transcriptPath: json['transcriptPath'] as String?,
      photoPath: json['photoPath'] as String?,
      recommendationLetterPath: json['recommendationLetterPath'] as String?,
      motivationLetterPath: json['motivationLetterPath'] as String?,
      medicalCertificatePath: json['medicalCertificatePath'] as String?,
      otherDocumentsPath: json['otherDocumentsPath'] as String?,
      parentName: json['parentName'] as String?,
      parentPhone: json['parentPhone'] as String?,
      parentEmail: json['parentEmail'] as String?,
      parentOccupation: json['parentOccupation'] as String?,
      parentAddress: json['parentAddress'] as String?,
      parentRelationship: json['parentRelationship'] as String?,
      parentIncomeLevel: json['parentIncomeLevel'] as String?,
      paymentMethod: json['paymentMethod'] as String?,
      paymentReference: json['paymentReference'] as String?,
      paymentAmount: (json['paymentAmount'] as num?)?.toDouble(),
      paymentCurrency: json['paymentCurrency'] as String? ?? 'XAF',
      paymentDate: json['paymentDate'] == null
          ? null
          : DateTime.parse(json['paymentDate'] as String),
      paymentStatus: json['paymentStatus'] as String? ?? 'pending',
      paymentProofPath: json['paymentProofPath'] as String?,
      scholarshipRequested: json['scholarshipRequested'] as bool? ?? false,
      scholarshipType: json['scholarshipType'] as String?,
      financialAidAmount: (json['financialAidAmount'] as num?)?.toDouble(),
      status: json['status'] as String? ?? 'pending',
      documentsStatus: json['documentsStatus'] as String? ?? 'pending',
      reviewPriority: json['reviewPriority'] as String? ?? 'NORMAL',
      reviewedBy: (json['reviewedBy'] as num?)?.toInt(),
      reviewDate: json['reviewDate'] == null
          ? null
          : DateTime.parse(json['reviewDate'] as String),
      reviewComments: json['reviewComments'] as String?,
      rejectionReason: json['rejectionReason'] as String?,
      interviewRequired: json['interviewRequired'] as bool? ?? false,
      interviewDate: json['interviewDate'] == null
          ? null
          : DateTime.parse(json['interviewDate'] as String),
      interviewLocation: json['interviewLocation'] as String?,
      interviewType: json['interviewType'] as String?,
      interviewResult: json['interviewResult'] as String?,
      interviewNotes: json['interviewNotes'] as String?,
      admissionNumber: json['admissionNumber'] as String?,
      admissionDate: json['admissionDate'] == null
          ? null
          : DateTime.parse(json['admissionDate'] as String),
      registrationDeadline: json['registrationDeadline'] == null
          ? null
          : DateTime.parse(json['registrationDeadline'] as String),
      registrationCompleted: json['registrationCompleted'] as bool? ?? false,
      studentId: json['studentId'] as String?,
      batchNumber: json['batchNumber'] as String?,
      contactPreference: json['contactPreference'] as String?,
      marketingConsent: json['marketingConsent'] as bool? ?? false,
      dataProcessingConsent: json['dataProcessingConsent'] as bool? ?? false,
      newsletterSubscription: json['newsletterSubscription'] as bool? ?? false,
      ipAddress: json['ipAddress'] as String?,
      userAgent: json['userAgent'] as String?,
      deviceType: json['deviceType'] as String?,
      browserInfo: json['browserInfo'] as String?,
      osInfo: json['osInfo'] as String?,
      locationCountry: json['locationCountry'] as String?,
      locationCity: json['locationCity'] as String?,
      notes: json['notes'] as String?,
      adminNotes: json['adminNotes'] as String?,
      internalComments: json['internalComments'] as String?,
      specialNeeds: json['specialNeeds'] as String?,
      medicalConditions: json['medicalConditions'] as String?,
      submissionDate: DateTime.parse(json['submissionDate'] as String),
      lastUpdated: DateTime.parse(json['lastUpdated'] as String),
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: DateTime.parse(json['updatedAt'] as String),
      deletedAt: json['deletedAt'] == null
          ? null
          : DateTime.parse(json['deletedAt'] as String),
    );

Map<String, dynamic> _$PreinscriptionModelToJson(
        PreinscriptionModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'uuid': instance.uuid,
      'uniqueCode': instance.uniqueCode,
      'faculty': instance.faculty,
      'lastName': instance.lastName,
      'firstName': instance.firstName,
      'middleName': instance.middleName,
      'dateOfBirth': instance.dateOfBirth.toIso8601String(),
      'isBirthDateOnCertificate': instance.isBirthDateOnCertificate,
      'placeOfBirth': instance.placeOfBirth,
      'gender': instance.gender,
      'cniNumber': instance.cniNumber,
      'residenceAddress': instance.residenceAddress,
      'maritalStatus': instance.maritalStatus,
      'phoneNumber': instance.phoneNumber,
      'email': instance.email,
      'firstLanguage': instance.firstLanguage,
      'professionalSituation': instance.professionalSituation,
      'previousDiploma': instance.previousDiploma,
      'previousInstitution': instance.previousInstitution,
      'graduationYear': instance.graduationYear,
      'graduationMonth': instance.graduationMonth,
      'desiredProgram': instance.desiredProgram,
      'studyLevel': instance.studyLevel,
      'specialization': instance.specialization,
      'seriesBac': instance.seriesBac,
      'bacYear': instance.bacYear,
      'bacCenter': instance.bacCenter,
      'bacMention': instance.bacMention,
      'gpaScore': instance.gpaScore,
      'rankInClass': instance.rankInClass,
      'birthCertificatePath': instance.birthCertificatePath,
      'cniPath': instance.cniPath,
      'diplomaPath': instance.diplomaPath,
      'transcriptPath': instance.transcriptPath,
      'photoPath': instance.photoPath,
      'recommendationLetterPath': instance.recommendationLetterPath,
      'motivationLetterPath': instance.motivationLetterPath,
      'medicalCertificatePath': instance.medicalCertificatePath,
      'otherDocumentsPath': instance.otherDocumentsPath,
      'parentName': instance.parentName,
      'parentPhone': instance.parentPhone,
      'parentEmail': instance.parentEmail,
      'parentOccupation': instance.parentOccupation,
      'parentAddress': instance.parentAddress,
      'parentRelationship': instance.parentRelationship,
      'parentIncomeLevel': instance.parentIncomeLevel,
      'paymentMethod': instance.paymentMethod,
      'paymentReference': instance.paymentReference,
      'paymentAmount': instance.paymentAmount,
      'paymentCurrency': instance.paymentCurrency,
      'paymentDate': instance.paymentDate?.toIso8601String(),
      'paymentStatus': instance.paymentStatus,
      'paymentProofPath': instance.paymentProofPath,
      'scholarshipRequested': instance.scholarshipRequested,
      'scholarshipType': instance.scholarshipType,
      'financialAidAmount': instance.financialAidAmount,
      'status': instance.status,
      'documentsStatus': instance.documentsStatus,
      'reviewPriority': instance.reviewPriority,
      'reviewedBy': instance.reviewedBy,
      'reviewDate': instance.reviewDate?.toIso8601String(),
      'reviewComments': instance.reviewComments,
      'rejectionReason': instance.rejectionReason,
      'interviewRequired': instance.interviewRequired,
      'interviewDate': instance.interviewDate?.toIso8601String(),
      'interviewLocation': instance.interviewLocation,
      'interviewType': instance.interviewType,
      'interviewResult': instance.interviewResult,
      'interviewNotes': instance.interviewNotes,
      'admissionNumber': instance.admissionNumber,
      'admissionDate': instance.admissionDate?.toIso8601String(),
      'registrationDeadline': instance.registrationDeadline?.toIso8601String(),
      'registrationCompleted': instance.registrationCompleted,
      'studentId': instance.studentId,
      'batchNumber': instance.batchNumber,
      'contactPreference': instance.contactPreference,
      'marketingConsent': instance.marketingConsent,
      'dataProcessingConsent': instance.dataProcessingConsent,
      'newsletterSubscription': instance.newsletterSubscription,
      'ipAddress': instance.ipAddress,
      'userAgent': instance.userAgent,
      'deviceType': instance.deviceType,
      'browserInfo': instance.browserInfo,
      'osInfo': instance.osInfo,
      'locationCountry': instance.locationCountry,
      'locationCity': instance.locationCity,
      'notes': instance.notes,
      'adminNotes': instance.adminNotes,
      'internalComments': instance.internalComments,
      'specialNeeds': instance.specialNeeds,
      'medicalConditions': instance.medicalConditions,
      'submissionDate': instance.submissionDate.toIso8601String(),
      'lastUpdated': instance.lastUpdated.toIso8601String(),
      'createdAt': instance.createdAt.toIso8601String(),
      'updatedAt': instance.updatedAt.toIso8601String(),
      'deletedAt': instance.deletedAt?.toIso8601String(),
    };
