-- Insertion des rôles dans la nouvelle table roles avec UUID et codes
INSERT INTO `roles` (
    `id`, `uuid`, `code`, `name`, `display_name`, `category`, `level`, 
    `description`, `responsibilities`, `permissions`, `is_active`, `is_system_role`, 
    `parent_role_id`, `institution_type`, `ministry_affiliation`, `created_at`, `updated_at`
) VALUES
(1, UUID(), 'superadmin', 'superadmin', 'Super Administrateur', 'national_institutional', 100, 
 'Accès complet plateforme', 
 '{"platform_management": true, "user_management": true, "system_configuration": true, "audit_logs": true}',
 '{"all": true}', 1, 1, NULL, 'all', NULL, '2025-11-24 06:15:14', '2025-11-24 06:15:14'),
(2, UUID(), 'admin_national', 'admin_national', 'Administrateur National', 'national_institutional', 90, 
 'Gestion MINESUP', 
 '{"national_policy": true, "university_oversight": true, "accreditation": true, "reporting": true}',
 '{"national": true, "universities": true, "institutions": true}', 1, 1, NULL, 'all', 'MINESUP', '2025-11-24 06:15:14', '2025-11-24 06:15:14'),
(3, UUID(), 'admin_local', 'admin_local', 'Administrateur Local', 'university_hierarchy', 80, 
 'Gestion université', 
 '{"university_management": true, "department_management": true, "student_affairs": true, "staff_management": true}',
 '{"university": true, "departments": true, "users": true, "courses": true}', 1, 1, NULL, 'all', NULL, '2025-11-24 06:15:14', '2025-11-24 06:15:14'),
(4, UUID(), 'teacher', 'teacher', 'Enseignant', 'teaching_staff', 50, 
 'Enseignant universitaire', 
 '{"course_management": true, "student_evaluation": true, "research": true, "academic_advising": true}',
 '{"courses": true, "students": true, "grades": true, "research": true}', 1, 0, NULL, 'all', NULL, '2025-11-24 06:15:14', '2025-11-24 06:15:14'),
(5, UUID(), 'leader', 'leader', 'Leader Étudiant', 'student_representation', 40, 
 'Responsable groupe', 
 '{"group_management": true, "event_organization": true, "peer_mentoring": true, "representation": true}',
 '{"groups": true, "events": true, "communication": true}', 1, 0, NULL, 'all', NULL, '2025-11-24 06:15:14', '2025-11-24 06:15:14'),
(6, UUID(), 'student', 'student', 'Étudiant', 'academic', 10, 
 'Étudiant standard', 
 '{"course_enrollment": true, "assignment_submission": true, "exam_participation": true, "collaboration": true}',
 '{"courses": true, "assignments": true, "exams": true, "messaging": true}', 1, 0, NULL, 'all', NULL, '2025-11-24 06:15:14', '2025-11-24 06:15:14'),
(7, UUID(), 'moderator', 'moderator', 'Modérateur', 'support_services', 60, 
 'Modérateur contenu', 
 '{"content_moderation": true, "user_support": true, "conflict_resolution": true, "community_management": true}',
 '{"content": true, "users": true, "reports": true, "moderation": true}', 1, 0, NULL, 'all', NULL, '2025-11-24 06:15:14', '2025-11-24 06:15:14'),
(8, UUID(), 'staff', 'staff', 'Personnel', 'administrative_technical', 30, 
 'Personnel administratif', 
 '{"administrative_tasks": true, "document_management": true, "schedule_management": true, "support": true}',
 '{"documents": true, "schedules": true, "administration": true}', 1, 0, NULL, 'all', NULL, '2025-11-24 06:15:14', '2025-11-24 06:15:14'),
(9, UUID(), 'invite', 'invite', 'Invité', 'partners_social', 0, 
 'Accès limité en lecture seule', 
 '{"view_content": true, "attend_events": true, "basic_communication": true}',
 '{"view": true, "events": true, "basic": true}', 1, 0, NULL, 'all', NULL, '2025-12-18 14:23:54', '2025-12-18 14:23:54');
