-- Migration pour la gestion complète des étudiants
-- Date: 2025-12-15
-- Description: Tables supplémentaires pour le module de gestion des étudiants

-- Table pour les inscriptions académiques par semestre
DROP TABLE IF EXISTS `student_enrollments`;
CREATE TABLE IF NOT EXISTS `student_enrollments` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `student_profile_id` bigint UNSIGNED NOT NULL,
  `academic_year_id` bigint UNSIGNED NOT NULL,
  `semester` enum('semester1','semester2') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `program_id` bigint UNSIGNED NOT NULL,
  `level` enum('licence1','licence2','licence3','master1','master2','doctorat1','doctorat2','doctorat3') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `enrollment_status` enum('enrolled','deferred','suspended','withdrawn','completed') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'enrolled',
  `enrollment_date` date NOT NULL,
  `completion_date` date DEFAULT NULL,
  `gpa_semester` decimal(3,2) DEFAULT NULL,
  `credits_attempted` int UNSIGNED DEFAULT '0',
  `credits_earned` int UNSIGNED DEFAULT '0',
  `attendance_rate` decimal(5,2) DEFAULT NULL,
  `tuition_fee_status` enum('unpaid','partial','paid','scholarship','exempt') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'unpaid',
  `tuition_amount` decimal(10,2) DEFAULT '0.00',
  `amount_paid` decimal(10,2) DEFAULT '0.00',
  `scholarship_amount` decimal(10,2) DEFAULT '0.00',
  `notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `unique_student_semester` (`student_profile_id`,`academic_year_id`,`semester`),
  KEY `idx_student_profile` (`student_profile_id`),
  KEY `idx_academic_year` (`academic_year_id`),
  KEY `idx_program` (`program_id`),
  KEY `idx_level` (`level`),
  KEY `idx_status` (`enrollment_status`),
  FOREIGN KEY (`student_profile_id`) REFERENCES `student_profiles`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years`(`id`) ON DELETE RESTRICT,
  FOREIGN KEY (`program_id`) REFERENCES `programs`(`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table pour les cours suivis par les étudiants
DROP TABLE IF EXISTS `student_courses`;
CREATE TABLE IF NOT EXISTS `student_courses` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `student_profile_id` bigint UNSIGNED NOT NULL,
  `course_id` bigint UNSIGNED NOT NULL,
  `enrollment_id` bigint UNSIGNED NOT NULL,
  `registration_status` enum('registered','dropped','completed','failed') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'registered',
  `registration_date` date NOT NULL,
  `final_grade` decimal(5,2) DEFAULT NULL,
  `grade_points` decimal(3,2) DEFAULT NULL,
  `credits_earned` decimal(3,1) DEFAULT '0.0',
  `attendance_count` int UNSIGNED DEFAULT '0',
  `total_sessions` int UNSIGNED DEFAULT '0',
  `assignment_grade` decimal(5,2) DEFAULT NULL,
  `midterm_grade` decimal(5,2) DEFAULT NULL,
  `final_exam_grade` decimal(5,2) DEFAULT NULL,
  `notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `unique_student_course_enrollment` (`student_profile_id`,`course_id`,`enrollment_id`),
  KEY `idx_student_profile` (`student_profile_id`),
  KEY `idx_course` (`course_id`),
  KEY `idx_enrollment` (`enrollment_id`),
  KEY `idx_status` (`registration_status`),
  FOREIGN KEY (`student_profile_id`) REFERENCES `student_profiles`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`enrollment_id`) REFERENCES `student_enrollments`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table pour les résultats académiques
DROP TABLE IF EXISTS `academic_records`;
CREATE TABLE IF NOT EXISTS `academic_records` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `student_profile_id` bigint UNSIGNED NOT NULL,
  `enrollment_id` bigint UNSIGNED NOT NULL,
  `record_type` enum('semester','annual','final') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `academic_year_id` bigint UNSIGNED NOT NULL,
  `semester` enum('semester1','semester2','annual') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `level` enum('licence1','licence2','licence3','master1','master2','doctorat1','doctorat2','doctorat3') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `gpa` decimal(3,2) DEFAULT NULL,
  `total_credits` int UNSIGNED DEFAULT '0',
  `earned_credits` int UNSIGNED DEFAULT '0',
  `class_rank` int UNSIGNED DEFAULT NULL,
  `total_students` int UNSIGNED DEFAULT NULL,
  `honors_status` enum('none','honors','high_honors','highest_honors') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'none',
  `academic_standing` enum('excellent','good','satisfactory','probation','warning') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'good',
  `decision` enum('promoted','repeat','conditional_promotion','suspended','expelled') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'promoted',
  `transcript_generated` tinyint(1) NOT NULL DEFAULT '0',
  `transcript_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `unique_student_record` (`student_profile_id`,`academic_year_id`,`semester`,`record_type`),
  KEY `idx_student_profile` (`student_profile_id`),
  KEY `idx_academic_year` (`academic_year_id`),
  KEY `idx_level` (`level`),
  KEY `idx_gpa` (`gpa`),
  FOREIGN KEY (`student_profile_id`) REFERENCES `student_profiles`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`enrollment_id`) REFERENCES `student_enrollments`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years`(`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table pour les documents des étudiants
DROP TABLE IF EXISTS `student_documents`;
CREATE TABLE IF NOT EXISTS `student_documents` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `student_profile_id` bigint UNSIGNED NOT NULL,
  `document_type` enum('birth_certificate','national_id','transcript','diploma','certificate','medical_form','insurance','photo','signature','other') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `document_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_size` bigint UNSIGNED DEFAULT NULL,
  `mime_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `upload_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expiry_date` date DEFAULT NULL,
  `status` enum('pending','verified','rejected','expired') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'pending',
  `verified_by` bigint UNSIGNED DEFAULT NULL,
  `verified_at` timestamp NULL DEFAULT NULL,
  `rejection_reason` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `is_required` tinyint(1) NOT NULL DEFAULT '0',
  `notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `idx_student_profile` (`student_profile_id`),
  KEY `idx_document_type` (`document_type`),
  KEY `idx_status` (`status`),
  KEY `idx_upload_date` (`upload_date`),
  FOREIGN KEY (`student_profile_id`) REFERENCES `student_profiles`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`verified_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table pour la discipline des étudiants
DROP TABLE IF EXISTS `student_discipline`;
CREATE TABLE IF NOT EXISTS `student_discipline` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `student_profile_id` bigint UNSIGNED NOT NULL,
  `incident_type` enum('attendance','behavior','academic_honesty','misconduct','other') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `severity_level` enum('warning','minor','major','severe','critical') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `incident_date` date NOT NULL,
  `incident_location` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `witnesses` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `evidence` json DEFAULT NULL,
  `sanction_type` enum('none','warning','probation','suspension','expulsion','community_service','counseling') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'none',
  `sanction_duration` int UNSIGNED DEFAULT NULL,
  `sanction_start_date` date DEFAULT NULL,
  `sanction_end_date` date DEFAULT NULL,
  `status` enum('pending','investigation','resolved','appealed','closed') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'pending',
  `reported_by` bigint UNSIGNED NOT NULL,
  `investigated_by` bigint UNSIGNED DEFAULT NULL,
  `resolved_by` bigint UNSIGNED DEFAULT NULL,
  `resolution_notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `appeal_deadline` date DEFAULT NULL,
  `appeal_status` enum('none','filed','under_review','upheld','rejected') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'none',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `idx_student_profile` (`student_profile_id`),
  KEY `idx_incident_type` (`incident_type`),
  KEY `idx_severity` (`severity_level`),
  KEY `idx_status` (`status`),
  KEY `idx_incident_date` (`incident_date`),
  FOREIGN KEY (`student_profile_id`) REFERENCES `student_profiles`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`reported_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT,
  FOREIGN KEY (`investigated_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`resolved_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table pour les bourses et aides financières
DROP TABLE IF EXISTS `student_scholarships`;
CREATE TABLE IF NOT EXISTS `student_scholarships` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `student_profile_id` bigint UNSIGNED NOT NULL,
  `scholarship_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `scholarship_type` enum('merit','need','athletic','government','private','institutional') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `provider` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount_per_year` decimal(10,2) DEFAULT '0.00',
  `amount_per_semester` decimal(10,2) DEFAULT '0.00',
  `coverage_percentage` decimal(5,2) DEFAULT '0.00',
  `duration_years` int UNSIGNED DEFAULT NULL,
  `renewal_conditions` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `academic_requirements` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `application_date` date DEFAULT NULL,
  `award_date` date DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `status` enum('applied','awarded','active','suspended','terminated','completed') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'applied',
  `renewal_status` enum('not_applicable','pending_renewal','renewed','not_renewed') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'not_applicable',
  `gpa_requirement` decimal(3,2) DEFAULT NULL,
  `notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `idx_student_profile` (`student_profile_id`),
  KEY `idx_scholarship_type` (`scholarship_type`),
  KEY `idx_status` (`status`),
  KEY `idx_award_date` (`award_date`),
  FOREIGN KEY (`student_profile_id`) REFERENCES `student_profiles`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table pour les statistiques des étudiants par institution
DROP TABLE IF EXISTS `student_statistics`;
CREATE TABLE IF NOT EXISTS `student_statistics` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `institution_id` bigint UNSIGNED NOT NULL,
  `faculty_id` bigint UNSIGNED DEFAULT NULL,
  `department_id` bigint UNSIGNED DEFAULT NULL,
  `program_id` bigint UNSIGNED DEFAULT NULL,
  `academic_year_id` bigint UNSIGNED NOT NULL,
  `level` enum('licence1','licence2','licence3','master1','master2','doctorat1','doctorat2','doctorat3','all') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `gender` enum('male','female','all') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'all',
  `total_students` int UNSIGNED NOT NULL DEFAULT '0',
  `active_students` int UNSIGNED NOT NULL DEFAULT '0',
  `graduated_students` int UNSIGNED NOT NULL DEFAULT '0',
  `withdrawn_students` int UNSIGNED NOT NULL DEFAULT '0',
  `suspended_students` int UNSIGNED NOT NULL DEFAULT '0',
  `average_gpa` decimal(3,2) DEFAULT NULL,
  `average_age` decimal(4,1) DEFAULT NULL,
  `international_students` int UNSIGNED NOT NULL DEFAULT '0',
  `scholarship_students` int UNSIGNED NOT NULL DEFAULT '0',
  `statistics_date` date NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `unique_statistic_record` (`institution_id`,`faculty_id`,`department_id`,`program_id`,`academic_year_id`,`level`,`gender`,`statistics_date`),
  KEY `idx_institution` (`institution_id`),
  KEY `idx_faculty` (`faculty_id`),
  KEY `idx_department` (`department_id`),
  KEY `idx_program` (`program_id`),
  KEY `idx_academic_year` (`academic_year_id`),
  KEY `idx_level` (`level`),
  KEY `idx_statistics_date` (`statistics_date`),
  FOREIGN KEY (`institution_id`) REFERENCES `institutions`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`faculty_id`) REFERENCES `faculties`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`department_id`) REFERENCES `departments`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`program_id`) REFERENCES `programs`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

