-- Table preinscriptions avec index optimisés pour éviter l'erreur de longueur de clé
-- MySQL/MariaDB a une limite de 1000 bytes pour les index

DROP TABLE IF EXISTS `preinscriptions`;
CREATE TABLE IF NOT EXISTS `preinscriptions` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID unique de la préinscription',
  `uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'UUID universel unique',
  `unique_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Code unique de référence',
  `faculty` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Faculté visée (UY1, FALSH, FS, FSE, IUT, ENSPY)',
  `last_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nom de famille',
  `first_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Prénom',
  `middle_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Autre prénom',
  `date_of_birth` date NOT NULL COMMENT 'Date de naissance',
  `is_birth_date_on_certificate` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'La date de naissance correspond-elle au certificat ?',
  `place_of_birth` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Lieu de naissance',
  `gender` enum('MASCULIN','FEMININ') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Genre',
  `cni_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Numéro CNI/PI',
  `residence_address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Adresse de résidence',
  `marital_status` enum('CELIBATAIRE','MARIE(E)','DIVORCE(E)','VEUF(VE)') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Situation maritale',
  `phone_number` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Numéro de téléphone',
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Adresse email',
  `first_language` enum('FRANÇAIS','ANGLAIS','BILINGUE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Première langue',
  `professional_situation` enum('SANS EMPLOI','SALARIE(E)','EN AUTO-EMPLOI','STAGIAIRE','RETRAITE(E)') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Situation professionnelle',
  `previous_diploma` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Diplôme précédent (BAC, GCE, BREVET, etc.)',
  `previous_institution` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Établissement précédent',
  `graduation_year` int DEFAULT NULL COMMENT 'Année d''obtention du diplôme',
  `graduation_month` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Mois d''obtention',
  `desired_program` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Programme souhaité',
  `study_level` enum('LICENCE','MASTER','DOCTORAT','DUT','BTS','MASTER_PRO','DEUST','AUTRE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Niveau d''études visé',
  `specialization` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Spécialisation souhaitée',
  `series_bac` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Série du BAC (A, B, C, D, E, F, G, H, TI)',
  `bac_year` int DEFAULT NULL COMMENT 'Année du BAC',
  `bac_center` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Centre d''examen BAC',
  `bac_mention` enum('PASSABLE','ASSEZ_BIEN','BIEN','TRES_BIEN','EXCELLENT') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Mention au BAC',
  `gpa_score` decimal(4,2) DEFAULT NULL COMMENT 'Score GPA si applicable',
  `rank_in_class` int DEFAULT NULL COMMENT 'Rang dans la classe',
  `birth_certificate_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Chemin certificat naissance',
  `cni_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Chemin CNI/PI',
  `diploma_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Chemin diplôme',
  `transcript_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Chemin relevé de notes',
  `photo_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Chemin photo d''identité',
  `recommendation_letter_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Chemin lettre de recommandation',
  `motivation_letter_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Chemin lettre de motivation',
  `medical_certificate_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Chemin certificat médical',
  `other_documents_path` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Chemins autres documents (JSON)',
  `parent_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Nom complet du parent/tuteur',
  `parent_phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Téléphone du parent',
  `parent_email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Email du parent',
  `parent_occupation` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Profession du parent',
  `parent_address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Adresse du parent',
  `parent_relationship` enum('PERE','MERE','TUTEUR','AUTRE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Lien avec le parent',
  `parent_income_level` enum('FAIBLE','MOYEN','ELEVE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Niveau de revenu du parent',
  `payment_method` enum('ORANGE_MONEY','MTN_MONEY','BANK_TRANSFER','CASH','MOBILE_MONEY','CHEQUE','OTHER') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Méthode de paiement',
  `payment_reference` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Référence de paiement',
  `payment_amount` decimal(10,2) DEFAULT NULL COMMENT 'Montant payé',
  `payment_currency` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'XAF' COMMENT 'Devise du paiement',
  `payment_date` timestamp NULL DEFAULT NULL COMMENT 'Date de paiement',
  `payment_status` enum('pending','paid','confirmed','refunded','partial') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending' COMMENT 'Statut du paiement',
  `payment_proof_path` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Chemin preuve de paiement',
  `scholarship_requested` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Bourse demandée ?',
  `scholarship_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Type de bourse',
  `financial_aid_amount` decimal(10,2) DEFAULT NULL COMMENT 'Montant aide financière',
  `status` enum('pending','under_review','accepted','rejected','cancelled','deferred','waitlisted') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending' COMMENT 'Statut global',
  `documents_status` enum('pending','submitted','verified','incomplete','rejected') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending' COMMENT 'Statut des documents',
  `review_priority` enum('LOW','NORMAL','HIGH','URGENT') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NORMAL' COMMENT 'Priorité de révision',
  `reviewed_by` bigint UNSIGNED DEFAULT NULL COMMENT 'ID de l''administrateur qui a validé',
  `review_date` timestamp NULL DEFAULT NULL COMMENT 'Date de validation/rejet',
  `review_comments` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Commentaires de révision',
  `rejection_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Motif de rejet',
  `interview_required` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Entretien requis ?',
  `interview_date` timestamp NULL DEFAULT NULL COMMENT 'Date d''entretien',
  `interview_location` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Lieu d''entretien',
  `interview_type` enum('PHYSICAL','ONLINE','PHONE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Type d''entretien',
  `interview_result` enum('PENDING','PASSED','FAILED','NO_SHOW') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Résultat entretien',
  `interview_notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Notes entretien',
  `admission_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Numéro d''admission si accepté',
  `admission_date` timestamp NULL DEFAULT NULL COMMENT 'Date d''admission',
  `registration_deadline` date DEFAULT NULL COMMENT 'Date limite pour inscription définitive',
  `registration_completed` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Inscription complétée ?',
  `student_id` bigint UNSIGNED DEFAULT NULL COMMENT 'ID étudiant final - lié à la table users',
  `batch_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Numéro de promotion',
  `contact_preference` enum('EMAIL','PHONE','SMS','WHATSAPP') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Préférence de contact',
  `marketing_consent` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Consentement marketing ?',
  `data_processing_consent` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Consentement traitement données ?',
  `newsletter_subscription` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Abonnement newsletter ?',
  `ip_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Adresse IP de soumission',
  `user_agent` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Navigateur utilisé',
  `device_type` enum('DESKTOP','MOBILE','TABLET','OTHER') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Type d''appareil',
  `browser_info` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Informations navigateur',
  `os_info` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Système d''exploitation',
  `location_country` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Pays de soumission',
  `location_city` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Ville de soumission',
  `notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Notes générales',
  `admin_notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Notes administrateur',
  `internal_comments` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Commentaires internes',
  `special_needs` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Besoins spéciaux',
  `medical_conditions` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Conditions médicales',
  `submission_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date de soumission',
  `last_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Dernière mise à jour',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date de création',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Date de modification',
  `deleted_at` timestamp NULL DEFAULT NULL COMMENT 'Date de suppression (soft delete)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_unique_code` (`unique_code`),
  UNIQUE KEY `idx_uuid` (`uuid`),
  UNIQUE KEY `idx_admission_number` (`admission_number`),
  UNIQUE KEY `idx_student_id` (`student_id`),
  KEY `idx_faculty` (`faculty`(191)),
  KEY `idx_status` (`status`),
  KEY `idx_payment_status` (`payment_status`),
  KEY `idx_documents_status` (`documents_status`),
  KEY `idx_submission_date` (`submission_date`),
  KEY `idx_email` (`email`(191)),
  KEY `idx_phone` (`phone_number`),
  KEY `idx_desired_program` (`desired_program`(191)),
  KEY `idx_study_level` (`study_level`),
  KEY `idx_graduation_year` (`graduation_year`),
  KEY `idx_payment_method` (`payment_method`),
  KEY `idx_review_date` (`review_date`),
  KEY `idx_reviewed_by` (`reviewed_by`),
  KEY `idx_payment_date` (`payment_date`),
  KEY `idx_interview_date` (`interview_date`),
  KEY `idx_admission_date` (`admission_date`),
  KEY `idx_registration_deadline` (`registration_deadline`),
  KEY `idx_parent_phone` (`parent_phone`),
  KEY `idx_parent_email` (`parent_email`(191)),
  KEY `idx_batch_number` (`batch_number`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_updated_at` (`updated_at`),
  KEY `idx_faculty_status` (`faculty`(191),`status`),
  KEY `idx_program_level` (`desired_program`(191),`study_level`),
  KEY `idx_payment_status_date` (`payment_status`,`payment_date`),
  KEY `idx_review_status_date` (`status`,`review_date`),
  KEY `idx_student_id_fk` (`student_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Ajouter la contrainte de clé étrangère après la création de la table
ALTER TABLE `preinscriptions` 
ADD CONSTRAINT `fk_preinscriptions_student_id` 
FOREIGN KEY (`student_id`) REFERENCES `users` (`id`) 
ON DELETE SET NULL ON UPDATE CASCADE;
